server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tes_springboot
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # create-drop, create, update, validate, none
    show-sql: true # Tampilkan SQL queries di console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Optional: JPA naming strategy
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl